development: 
  cloud_name: "gameonics"
  api_key: <%= ENV['CLOUDINARY_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_SECRET'] %>
  secure: true
  enhance_image_tag: true
  static_file_support: true

production:
  cloud_name: "gameonics"
  api_key: <%= ENV['CLOUDINARY_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_SECRET'] %>
  secure: true
  enhance_image_tag: true
  static_file_support: true
